### ISSUE TITLE
Isso funcionava bem ate a versão 94 do Chrome

### ISSUE THREAD

**Issue by elvispdosreis** [rafaelcouto/integrando-aplicacao-web-com-dispositivo-local#1]
Devido a ultima atualização do Chrome para versão 94 isso não deverá mais funcionar

CORS-RFC1918

https://developer.chrome.com/blog/private-network-access-update/

**Comment by rafaelcouto** [comment]
![image](https://user-images.githubusercontent.com/700170/139555438-afd7319e-7b52-4ff9-8070-70400a0e7fc4.png)

Se o endereço da aplicação web for HTTPS, continua funcionando normalmente. Fiz o teste aqui utilizando a versão 95 e acessando o endereço que deixei de exemplo (https://artigos.rafaelcouto.com.br/integrando-aplicacao-web-com-dispositivo-local/).
